### ISSUE TITLE
iPhone X support

### ISSUE THREAD

**Issue by liberaltech** [silviolleite/django-pwa#4]
Does this support iPhone X & Xs? I’ve been trying it with both but can only get it to work on older iPhones like the iphone 7.

Does anyone have any info on this?
Could this be an Apple issue?

**Comment by silviolleite** [comment]
Hello @liberaltech, are you talking about splash screen for iOS? 
If yes, I am working to add this feature 
If no, tell me more about your problem, give me more details please.

Maybe this link can help you learn more about PWA on iPhone [https://medium.com/@oieduardorabelo/pwa-no-ios-como-deix%C3%A1-lo-mais-nativo-e022f6c67b9c](https://medium.com/@oieduardorabelo/pwa-no-ios-como-deix%C3%A1-lo-mais-nativo-e022f6c67b9c)

**Comment by silviolleite** [comment]
I have updated the package and now the version 1.0.2 is accepting include splash screen for iOS.

**Comment by liberaltech** [comment]
The top search bar and bottom navigation bar are not hidden on iPhone X. 
I’m have “display:fullscreen” option in the settings.

**Comment by silviolleite** [comment]
You must trying to set it to `"display": "standalone"`.
You can see more about this setting in [https://developer.mozilla.org/pt-BR/docs/Web/Manifest#display](https://developer.mozilla.org/pt-BR/docs/Web/Manifest#display)

**Comment by liberaltech** [comment]
I have tried the default settings and manually setting display to "standalone" and still get the browser navigation top and bottom bars.

**Comment by liberaltech** [comment]
I have tried adding progressive apps like Rocket Chat to my iPhone XS and it doesn't appear in full screen like a native app. This tells me that it might be an iOS Safari issue with iPhone X and XS. Id be interested to see if anyone has had any luck adding a progressive web app to their home screen on an iPhone X or XS.

I tested my iPhone XS with apps from https://pwa.rocks and none of them appear to work in full screen like a native app.

**Comment by liberaltech** [comment]
@silviolleite , I was finally able to get this to work on an iPhone X & XS.

The reason why it wasn't working as a standalone app was because of what happens when you have too many apps installed on your Home Screen ( oops ). If you want to install a new app from the AppStore and your Home Screen is completely full iOS will remove the most unused app from the Home Screen but that is not the case if you want to install a PWA. After going through and deleting enough apps to see my Home Screen I tried installing my PWA and it worked. 🎉 👍 

If anyone is having trouble getting this to work make sure that you have enough space on your Home Screen and that the app is permanently being added or it wont be recognized as a PWA.

This issue can be closed
